server:
  port: 8091

spring:
  application:
    name: demo

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.119.124.105:3306/go-backend
    username: root
    password: root


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.demo.userRelationships.entity
