spring:
  application:
    name: messagepush
  datasource:
    url: jdbc:mysql://localhost:3306/elysium-link
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379


server:
  port: 8090
